export class GlobalCounter {
	static #instance: GlobalCounter;
	private count: number = 0;
	private constructor(current_step?: number) {
		// HistoryService will pass the path of history repository to GlobalCounter, and GlobalCounter will use this path to generate the id of history entry. The id is generated by combining the path and the count. This can ensure the uniqueness of the id.
		if (current_step) {
			this.count = current_step;
		}
	}

	public static getGlobalCounter(currentStep?: number): GlobalCounter {
		if (!GlobalCounter.#instance) {
			GlobalCounter.#instance = new GlobalCounter(currentStep);
		}
		return GlobalCounter.#instance;
	}

	public initialize(current_step: number): void {
		this.count = current_step;
	}

	public getCount(): number {
		return this.count;
	}

	public increment(): number {
		this.count++;
		return this.count;

	}

	public decrement(): number {
		this.count--;
		return this.count;
	}
}
